name: flutter_sns
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #  https://pub.dev/packages/crypto
  crypto: ^3.0.3

  encrypt: ^5.0.3

  http:

  # https://pub:dev/packages/shared_preferences:
  shared_preferences: ^2.2.3

  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.3

  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.0

  multi_image_picker: ^4.8.01
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/uploads/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: BasicFont
      fonts:
        - asset: assets/fonts/basic_font.ttf
          weight: 100
